# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_room(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        add_room = QWidget()

        self.setObjectName("RemontIP")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(add_room)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(180, 10, 131, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setTabletTracking(False)
        self.text.setAcceptDrops(False)
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setLineWidth(1)
        self.text.setTextFormat(QtCore.Qt.AutoText)
        self.text.setScaledContents(False)
        self.text.setObjectName("text")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 20, 30, 30))
        self.back_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.back_btn.clicked.connect(lambda: self.controller.showCreateFlat())

        self.calculate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_btn.setGeometry(QtCore.QRect(80, 350, 171, 51))
        self.calculate_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.calculate_btn.setObjectName("calculate_btn")
        self.Room_type = QtWidgets.QLineEdit(self.centralwidget)
        self.Room_type.setGeometry(QtCore.QRect(100, 130, 131, 31))
        self.Room_type.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Stencil\";\n"
"color: gray;\n"
"")
        self.Room_type.setFrame(True)
        self.Room_type.setObjectName("Room_type")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(100, 180, 131, 31))
        self.lineEdit_height.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Stencil\";\n"
"color: gray;\n"
"")
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.lineEdit_lenght = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lenght.setGeometry(QtCore.QRect(100, 230, 131, 31))
        self.lineEdit_lenght.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Stencil\";\n"
"color: gray;\n"
"")
        self.lineEdit_lenght.setObjectName("lineEdit_lenght")
        self.lineEdit_widht = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_widht.setGeometry(QtCore.QRect(100, 280, 131, 31))
        self.lineEdit_widht.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Stencil\";\n"
"color: gray;\n"
"")
        self.lineEdit_widht.setObjectName("lineEdit_widht")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(add_room)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.text.setText(_translate("RemontIP", "<html><head/><body><p><span style=\" font-size:24pt;\">Add Room</span></p></body></html>"))
        self.back_btn.setText(_translate("RemontIP", "<"))
        self.calculate_btn.setText(_translate("RemontIP", "Enter"))
        self.Room_type.setText(_translate("RemontIP", "Select type room..."))
        self.lineEdit_height.setText(_translate("RemontIP", "Enter height..."))
        self.lineEdit_lenght.setText(_translate("RemontIP", "Enter lenght..."))
        self.lineEdit_widht.setText(_translate("RemontIP", "Enter width..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_add_room()
    ui.setupUi(RemontIP)
    RemontIP.show()
    sys.exit(app.exec_())
