# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autorizet.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autorizet(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        autorizet = QWidget()

        self.setObjectName("RemontIP")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(autorizet)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(90, 260, 131, 51))
        self.create_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.create_btn.setObjectName("create_btn")
        self.create_btn.clicked.connect(lambda: self.controller.showCreate())

        self.log_in_btn = QtWidgets.QPushButton(self.centralwidget)
        self.log_in_btn.setGeometry(QtCore.QRect(90, 190, 131, 51))
        self.log_in_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.log_in_btn.setObjectName("log_in_btn")
        self.log_in_btn.clicked.connect(lambda: self.controller.showEnter())

        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(autorizet)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.create_btn.setText(_translate("RemontIP", "Create account"))
        self.log_in_btn.setText(_translate("RemontIP", "Log in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_autorizet()
    ui.setupUi(RemontIP)
    RemontIP.show()
    sys.exit(app.exec_())
