# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_scrin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_scrin(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        main_scrin = QWidget()

        self.setObjectName("MainWindow")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(main_scrin)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 70, 331, 161))
        self.image.setMinimumSize(QtCore.QSize(201, 0))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("view/screen/img/thumbnail.jpg.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.Create_flat_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_flat_btn.setGeometry(QtCore.QRect(80, 330, 171, 51))
        self.Create_flat_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.Create_flat_btn.setObjectName("Create_flat_btn")
        self.Create_flat_btn.clicked.connect(lambda: self.controller.showCreateFlat())

        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(120, 10, 191, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setTabletTracking(False)
        self.text.setAcceptDrops(False)
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setLineWidth(1)
        self.text.setTextFormat(QtCore.Qt.AutoText)
        self.text.setScaledContents(False)
        self.text.setObjectName("text")
        self.Perconal_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Perconal_btn.setGeometry(QtCore.QRect(80, 400, 171, 51))
        self.Perconal_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.Perconal_btn.setObjectName("Perconal_btn")
        self.setCentralWidget(self.centralwidget)

        self.Perconal_btn.clicked.connect(lambda: self.controller.showPerconal())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(main_scrin)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Create_flat_btn.setText(_translate("RemontIP", "Create Flat"))
        self.text.setText(_translate("RemontIP", "<html><head/><body><p><span style=\" font-size:24pt;\">Home Renovation</span></p></body></html>"))
        self.Perconal_btn.setText(_translate("RemontIP", "Personal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_main_scrin(1, 2)
    RemontIP.show()
    sys.exit(app.exec_())
