# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perconal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_perconal(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        perconal = QWidget()

        self.setObjectName("RemontIP")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(perconal)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(180, 10, 131, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setTabletTracking(False)
        self.text.setAcceptDrops(False)
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setLineWidth(1)
        self.text.setTextFormat(QtCore.Qt.AutoText)
        self.text.setScaledContents(False)
        self.text.setObjectName("text")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 20, 30, 30))
        self.back_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.back_btn.clicked.connect(lambda: self.controller.showMainScreen(1,2))

        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(50, 100, 241, 41))
        self.label_name.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: rgb(255, 255, 255);")
        self.label_name.setObjectName("label_name")
        self.label_surname = QtWidgets.QLabel(self.centralwidget)
        self.label_surname.setGeometry(QtCore.QRect(50, 150, 241, 41))
        self.label_surname.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: rgb(255, 255, 255);")
        self.label_surname.setObjectName("label_surname")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(50, 200, 241, 41))
        self.label_email.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: rgb(255, 255, 255);")
        self.label_email.setObjectName("label_email")
        self.label_phone = QtWidgets.QLabel(self.centralwidget)
        self.label_phone.setGeometry(QtCore.QRect(50, 250, 241, 41))
        self.label_phone.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: rgb(255, 255, 255);")
        self.label_phone.setObjectName("label_phone")
        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setGeometry(QtCore.QRect(50, 300, 241, 41))
        self.label_price.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: rgb(255, 255, 255);")
        self.label_price.setObjectName("label_price")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(perconal)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.text.setText(_translate("RemontIP", "<html><head/><body><p><span style=\" font-size:24pt;\">Personal</span></p></body></html>"))
        self.back_btn.setText(_translate("RemontIP", "<"))
        self.label_name.setText(_translate("RemontIP", "<html><head/><body><p align=\"center\">User name</p></body></html>"))
        self.label_surname.setText(_translate("RemontIP", "<html><head/><body><p align=\"center\">User surname</p></body></html>"))
        self.label_email.setText(_translate("RemontIP", "<html><head/><body><p align=\"center\">User e-mail</p></body></html>"))
        self.label_phone.setText(_translate("RemontIP", "<html><head/><body><p align=\"center\">Phone</p></body></html>"))
        self.label_price.setText(_translate("RemontIP", "<html><head/><body><p align=\"center\">Flat price</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_perconal()
    ui.setupUi(RemontIP)
    RemontIP.show()
    sys.exit(app.exec_())
