# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_type.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_type(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        select_type = QWidget()

        self.setObjectName("RemontIP")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(select_type)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(30, 70, 271, 161))
        self.image.setMinimumSize(QtCore.QSize(201, 0))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("view/screen/img/thumbnail-1.jpg.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.Redecoration_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Redecoration_btn.setGeometry(QtCore.QRect(80, 250, 171, 51))
        self.Redecoration_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.Redecoration_btn.setObjectName("Redecoration_btn")
        self.Redecoration_btn.clicked.connect(lambda: self.controller.showPrice())

        self.Overhaul_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Overhaul_btn.setGeometry(QtCore.QRect(80, 320, 171, 51))
        self.Overhaul_btn.setStyleSheet("background-color: rgba(61, 131, 90, 217);\n"
"color: rgb(255, 255, 255);")
        self.Overhaul_btn.setObjectName("Overhaul_btn")
        self.Overhaul_btn.clicked.connect(lambda: self.controller.showPrice())

        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(180, 10, 131, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setTabletTracking(False)
        self.text.setAcceptDrops(False)
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setLineWidth(1)
        self.text.setTextFormat(QtCore.Qt.AutoText)
        self.text.setScaledContents(False)
        self.text.setObjectName("text")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 20, 30, 30))
        self.back_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.clicked.connect(lambda: self.controller.showCreateFlat())

        self.back_btn.setObjectName("back_btn")
        self.Premium_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Premium_btn.setGeometry(QtCore.QRect(80, 390, 171, 51))
        self.Premium_btn.setStyleSheet("background-color: rgba(62, 132, 91, 217);\n"
"color: rgb(255, 255, 255);")
        self.Premium_btn.setObjectName("Premium_btn")
        self.Premium_btn.clicked.connect(lambda: self.controller.showPrice())

        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(select_type)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Redecoration_btn.setText(_translate("RemontIP", "Redecoration"))
        self.Overhaul_btn.setText(_translate("RemontIP", "Overhaul"))
        self.text.setText(_translate("RemontIP", "<html><head/><body><p><span style=\" font-size:24pt;\">Select Type</span></p></body></html>"))
        self.back_btn.setText(_translate("RemontIP", "<"))
        self.Premium_btn.setText(_translate("RemontIP", "Premium"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_select_type()
    ui.setupUi(RemontIP)
    RemontIP.show()
    sys.exit(app.exec_())
