# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'your_flat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_your_flat(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        your_flat = QWidget()

        self.setObjectName("RemontIP")
        self.resize(330, 480)
        self.centralwidget = QtWidgets.QWidget(your_flat)
        self.centralwidget.setStyleSheet("background-color: rgb(154, 151, 153);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(180, 10, 131, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text.sizePolicy().hasHeightForWidth())
        self.text.setSizePolicy(sizePolicy)
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setTabletTracking(False)
        self.text.setAcceptDrops(False)
        self.text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text.setStyleSheet("color: rgb(255, 255, 255);")
        self.text.setLineWidth(1)
        self.text.setTextFormat(QtCore.Qt.AutoText)
        self.text.setScaledContents(False)
        self.text.setObjectName("text")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 20, 30, 30))
        self.back_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.back_btn.clicked.connect(lambda: self.controller.showCreateFlat())
        self.label_border = QtWidgets.QLabel(self.centralwidget)
        self.label_border.setGeometry(QtCore.QRect(10, 90, 251, 81))
        self.label_border.setStyleSheet("border: 3px solid;\n"
"border-color: rgba(64, 138, 95, 217);\n"
"font: 10pt \"Stencil\";\n"
"color: black;")
        self.label_border.setText("")
        self.label_border.setObjectName("label_border")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(20, 100, 51, 51))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("../100445.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        self.label_type.setGeometry(QtCore.QRect(80, 100, 60, 16))
        self.label_type.setObjectName("label_type")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(80, 120, 91, 21))
        self.label_height.setObjectName("label_height")
        self.label_lenght = QtWidgets.QLabel(self.centralwidget)
        self.label_lenght.setGeometry(QtCore.QRect(80, 140, 91, 21))
        self.label_lenght.setObjectName("label_lenght")
        self.label_widht = QtWidgets.QLabel(self.centralwidget)
        self.label_widht.setGeometry(QtCore.QRect(170, 120, 81, 21))
        self.label_widht.setObjectName("label_widht")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(260, 90, 61, 81))
        self.delete_btn.setStyleSheet("border: 3px solid;\n"
"font: 40pt  \"Stencil\";\n"
"color: #00A676;\n"
"border-color: rgb(166, 66, 69, 217);")
        self.delete_btn.setObjectName("delete_btn")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(your_flat)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.text.setText(_translate("RemontIP", "<html><head/><body><p><span style=\" font-size:24pt;\">Your Flat</span></p></body></html>"))
        self.back_btn.setText(_translate("RemontIP", "<"))
        self.label_type.setText(_translate("RemontIP", "Type"))
        self.label_height.setText(_translate("RemontIP", "Height: 12.3m"))
        self.label_lenght.setText(_translate("RemontIP", "Lenght: 12.3m"))
        self.label_widht.setText(_translate("RemontIP", "Widht: 12.3m"))
        self.delete_btn.setText(_translate("RemontIP", "🗑️"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemontIP = QtWidgets.QMainWindow()
    ui = Ui_your_flat()
    ui.setupUi(RemontIP)
    RemontIP.show()
    sys.exit(app.exec_())
